version: "3" 

services:
  db: 
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 2020techc_root_password_1234
      MYSQL_USER: 2020techc_username
      MYSQL_PASSWORD: yuk00_password
      MYSQL_DATABASE: yuk00_db
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./etc/mysql/data:/var/lib/mysql
    - ./etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./etc/mysql/sql:/docker-entrypoint-initdb.d
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public/:/var/www/public/
    depends_on:
      - php
  php:
    container_name: php 
    build: ./
    volumes:
      - ./public/:/var/www/public/
   redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
